#!/bin/bash
# run sns on a pointing worth of data
vos_uri=$1
pointing=$2
chip=$3
basedir="HSC_May25-lsst"
stack_rerun="NHF1_sns_weighted"
diff_rerun="NHF1_diff"
ccd=`echo ${chip} | awk ' { printf("%03d",$1) } ' `
angle_max=10
angle_min=-10
angle_step=2.5
rate_min=0.5
rate_max=3.5
rate_step=0.5
while [ -true ] ; do vmkdir -p ${vos_uri}/STACKS_V2/${pointing} && break ; done
# while [ -true ] ; do vcp -v ${vos_uri}/DIFFS/${pointing}/DIFF-${ccd}.tbz ./ && break ; done 
# tar xvf DIFF-${ccd}.tbz || exit
for rate in `seq ${rate_min} ${rate_step} ${rate_max}`;
do
   for angle in `seq ${angle_min} ${angle_step} ${angle_max}`
   do
       daomop-sns `pwd`/HSC_May25-lsst \
	   --rerun ${diff_rerun}:${stack_rerun} \
	   --rate-min ${rate} \
	   --rate-max ${rate} \
	   --rate-step ${rate_step} \
	   --angle-min ${angle} \
	   --angle-max ${angle} \
	   --angle-step ${angle_step} \
	   --pointing ${pointing} \
	   --ccd ${chip} \
	   --mask \
   	   --clip 16 \
	   --log-level INFO  || exit
       while [ -true ] ; do vcp -v ${basedir}/rerun/${stack_rerun}/deepDiff/${pointing}/HSC-R2/STACK*.fits ${vos_uri}/STACKS_V2/${pointing}/ && break ; done
       rm ${basedir}/rerun/${stack_rerun}/deepDiff/${pointing}/HSC-R2/STACK*.fits || exit
   done
done
